name: Tarabut CICD
on: 
  push
        
jobs:
  Build_Push_DockerImage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        registry: dockerhub
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./app/Dockerfile
        push: true
        tags: faraaz/tarabut:test